# Makefile autogenerated by Dyi on April 21, 2016
#
# Main target: all
# Sources: 

.DEFAULT_GOAL := all


.PHONY: docs
docs: k-wdf2vjfr k-druopagd k-bdi9k6ic k-kbjomdfn k-wi0yu5li k-1kd3s41p


.PHONY: devloop
devloop: k-57lyqa2d k-vbw4hifc


.PHONY: buildloop
buildloop: k-nhblxt5c


.PHONY: testloop
testloop: k-es9h7y2q


.PHONY: stoploop
stoploop: k-1q7v6giy k-48gcbypl


.PHONY: build
build: k-ygbrfndj


.PHONY: start
start: k-lhgmcv9n


.PHONY: test
test: k-80g8fgsf k-0aymjrm1


.PHONY: test-local-endpoint
test-local-endpoint: k-jg6mvo4i k-r8odm4o7


.PHONY: update
update: k-tjr9r1rh


.PHONY: major
major: k-cjqaw0a9 k-ld163xyr k-o4n4urrx


.PHONY: minor
minor: k-3rnaofh5 k-o2fv2yr5 k-hpctfquy


.PHONY: patch
patch: k-pswim8t9 k-gimh3gvc k-o8rf88jw


.PHONY: prepare
prepare:




.PHONY: k-wdf2vjfr
k-wdf2vjfr:  
	./node_modules/.bin/git-hist history.md


.PHONY: k-druopagd
k-druopagd:  
	./node_modules/.bin/mustache package.json docs/readme.md | ./node_modules/.bin/stupid-replace '~USAGE~' -f docs/usage.md > readme.md


.PHONY: k-bdi9k6ic
k-bdi9k6ic:  
	cat history.md >> readme.md


.PHONY: k-kbjomdfn
k-kbjomdfn:  
	mkdir -p ./man/man1


.PHONY: k-wi0yu5li
k-wi0yu5li:  
	pandoc -s -f markdown -t man readme.md > ./man/man1/vz-dockerino.1


.PHONY: k-1kd3s41p
k-1kd3s41p:  
	-hub cm 'update docs and history.md'


.PHONY: k-57lyqa2d
k-57lyqa2d:  
	make buildloop &


.PHONY: k-vbw4hifc
k-vbw4hifc:  
	make testloop &


.PHONY: k-nhblxt5c
k-nhblxt5c:  
	./node_modules/.bin/babel src -d lib --watch --presets es2015,stage-2


.PHONY: k-es9h7y2q
k-es9h7y2q:  
	./node_modules/.bin/mocha -w ./lib/test.js


.PHONY: k-1q7v6giy
k-1q7v6giy:  
	-pkill -9 -f '.*mocha.*'


.PHONY: k-48gcbypl
k-48gcbypl:  
	-pkill -9 -f '.*babel.*watch.*'


.PHONY: k-ygbrfndj
k-ygbrfndj:  
	./node_modules/.bin/babel src -d lib --presets es2015,stage-2


.PHONY: k-6prfkncw
k-6prfkncw:  
	((echo '#!/usr/bin/env node') && cat ./lib/index.js) > index.js


.PHONY: k-kf2l5o9v
k-kf2l5o9v:  
	chmod +x ./index.js


.PHONY: all
all: 
	make build 
	make k-6prfkncw 
	make k-kf2l5o9v  


.PHONY: k-lhgmcv9n
k-lhgmcv9n:  
	npm start


.PHONY: k-80g8fgsf
k-80g8fgsf:  
	make all


.PHONY: k-0aymjrm1
k-0aymjrm1:  
	./node_modules/.bin/mocha ./lib/test.js


.PHONY: k-jg6mvo4i
k-jg6mvo4i:  
	make all


.PHONY: k-r8odm4o7
k-r8odm4o7:  
	mocha lib/testEndPoint.js


.PHONY: k-tjr9r1rh
k-tjr9r1rh:  
	make clean && ./node_modules/.bin/babel --presets es2015,stage-2 configure.js | node


.PHONY: k-cjqaw0a9
k-cjqaw0a9:  
	make all


.PHONY: k-ld163xyr
k-ld163xyr:  
	make docs


.PHONY: k-o4n4urrx
k-o4n4urrx:  
	./node_modules/.bin/xyz -i major


.PHONY: k-3rnaofh5
k-3rnaofh5:  
	make all


.PHONY: k-o2fv2yr5
k-o2fv2yr5:  
	make docs


.PHONY: k-hpctfquy
k-hpctfquy:  
	./node_modules/.bin/xyz -i minor


.PHONY: k-pswim8t9
k-pswim8t9:  
	make all


.PHONY: k-gimh3gvc
k-gimh3gvc:  
	make docs


.PHONY: k-o8rf88jw
k-o8rf88jw:  
	./node_modules/.bin/xyz -i patch


.PHONY: clean
clean:  




