# Makefile autogenerated by Dyi on October 19, 2017
#
# Main target: all
# Sources: 

.DEFAULT_GOAL := all


.PHONY: docs
docs: k-8fu9uddu k-ehacuqg3 k-ikyhylue k-bu43sad2 k-qklsls3t k-gd6hnv5r


.PHONY: devloop
devloop: k-ywjg30ii k-mhvq48ry


.PHONY: buildloop
buildloop: k-v2xouuhn


.PHONY: testloop
testloop: k-jordxt9w


.PHONY: stoploop
stoploop: k-bmcus3wh k-m4x9kupm


.PHONY: build
build: k-f86s6355


.PHONY: start
start: k-jqh1uje7


.PHONY: test
test: k-dxxtrt18 k-vbj7nuuj


.PHONY: test-local-endpoint
test-local-endpoint: k-8h6ls5wq k-8ehule5y


.PHONY: update
update: k-r5u3xeam


.PHONY: major
major: k-bg6lr80d k-eqxkgtew k-tcc4vl9w


.PHONY: minor
minor: k-l0jrrpqv k-ujy4d87i k-84f8j4ni


.PHONY: patch
patch: k-y3vtfmut k-bj3s7b7k k-cr03kjfi


.PHONY: prepare
prepare:




.PHONY: k-8fu9uddu
k-8fu9uddu:  
	./node_modules/.bin/git-hist history.md


.PHONY: k-ehacuqg3
k-ehacuqg3:  
	./node_modules/.bin/mustache package.json docs/readme.md | ./node_modules/.bin/stupid-replace '~USAGE~' -f docs/usage.md > readme.md


.PHONY: k-ikyhylue
k-ikyhylue:  
	cat history.md >> readme.md


.PHONY: k-bu43sad2
k-bu43sad2:  
	mkdir -p ./man/man1


.PHONY: k-qklsls3t
k-qklsls3t:  
	pandoc -s -f markdown -t man readme.md > ./man/man1/vz-dockerino.1


.PHONY: k-gd6hnv5r
k-gd6hnv5r:  
	-hub cm 'update docs and history.md'


.PHONY: k-ywjg30ii
k-ywjg30ii:  
	make buildloop &


.PHONY: k-mhvq48ry
k-mhvq48ry:  
	make testloop &


.PHONY: k-v2xouuhn
k-v2xouuhn:  
	./node_modules/.bin/babel src -d lib --watch --presets es2015,stage-2


.PHONY: k-jordxt9w
k-jordxt9w:  
	./node_modules/.bin/mocha -w ./lib/test.js


.PHONY: k-bmcus3wh
k-bmcus3wh:  
	-pkill -9 -f '.*mocha.*'


.PHONY: k-m4x9kupm
k-m4x9kupm:  
	-pkill -9 -f '.*babel.*watch.*'


.PHONY: k-f86s6355
k-f86s6355:  
	./node_modules/.bin/babel src -d lib --presets es2015,stage-2


.PHONY: k-xld5mktx
k-xld5mktx:  
	((echo '#!/usr/bin/env node') && cat ./lib/index.js) > index.js


.PHONY: k-r7o4b6l0
k-r7o4b6l0:  
	chmod +x ./index.js


.PHONY: all
all: 
	make build 
	make k-xld5mktx 
	make k-r7o4b6l0  


.PHONY: k-jqh1uje7
k-jqh1uje7:  
	npm start


.PHONY: k-dxxtrt18
k-dxxtrt18:  
	make all


.PHONY: k-vbj7nuuj
k-vbj7nuuj:  
	./node_modules/.bin/mocha ./lib/test.js


.PHONY: k-8h6ls5wq
k-8h6ls5wq:  
	make all


.PHONY: k-8ehule5y
k-8ehule5y:  
	mocha --no-timeouts lib/testEndPoint.js


.PHONY: k-r5u3xeam
k-r5u3xeam:  
	make clean && ./node_modules/.bin/babel --presets es2015,stage-2 configure.js | node


.PHONY: k-bg6lr80d
k-bg6lr80d:  
	make all


.PHONY: k-eqxkgtew
k-eqxkgtew:  
	make docs


.PHONY: k-tcc4vl9w
k-tcc4vl9w:  
	./node_modules/.bin/xyz -i major


.PHONY: k-l0jrrpqv
k-l0jrrpqv:  
	make all


.PHONY: k-ujy4d87i
k-ujy4d87i:  
	make docs


.PHONY: k-84f8j4ni
k-84f8j4ni:  
	./node_modules/.bin/xyz -i minor


.PHONY: k-y3vtfmut
k-y3vtfmut:  
	make all


.PHONY: k-bj3s7b7k
k-bj3s7b7k:  
	make docs


.PHONY: k-cr03kjfi
k-cr03kjfi:  
	./node_modules/.bin/xyz -i patch


.PHONY: clean
clean:  




