.TH "" "" "" "" ""
.SH vz\-dockerino
.RS
.PP
Small container to execute external student octave programs
.RE
.SS Install
.PP
Install it with
.IP
.nf
\f[C]
npm\ install\ vz\-dockerino
\f[]
.fi
.SS Usage
.IP
.nf
\f[C]
Usage:
\ \ \ \ vz\-dockerino\ [\ \-p\ PORT\ ]\ [\ \-n\ NUM\ ]\ [\ \-t\ SEC\ ]
\ \ \ \ vz\-dockerino\ (\ \-h\ |\ \-\-help\ )

Options:
\ \ \ \ \-h,\ \-\-help\ \ \ \ \ \ \ \ \ \ \ \ \ \ help\ for\ vz\-dockerino
\ \ \ \ \-p,\ \-\-port\ PORT\ \ \ \ \ \ \ \ \ port\ on\ which\ to\ listen\ (default:\ 3000)
\ \ \ \ \-n,\ \-\-number\ NUM\ \ \ \ \ \ \ \ number\ of\ concurrent\ requests\ that\ can\ be\ managed
\ \ \ \ \-t,\ \-\-timeout\ SEC\ \ \ \ \ \ \ timeout\ in\ seconds\ (default:\ 1)

Commands:

Arguments:
\f[]
.fi
.SS API
.PP
The server exposes two endpoints at port 3000
.SS \f[C]post\ /payload\f[]
.PP
Executes an EDX payload with the following schema:
.IP
.nf
\f[C]
{
\ \ \ \ code\ {
\ \ \ \ base,\ solution,\ validation,\ context,\ lang
\ \ \ \ }
\ \ \ \ response
}
\f[]
.fi
.PP
Answers:
.IP \[bu] 2
200 \- OK, result payload
.IP \[bu] 2
503 \- Server unavailable
.SS \f[C]post\ /status\f[]
.PP
No schema needed; returns:
.IP \[bu] 2
204 \- server ready
.IP \[bu] 2
503 \- Server unavailable (candidate for destruction)
.SS Todo
.PP
Add the following API endpoints:
.SS \f[C]post\ /kill\f[]
.IP \[bu] 2
Tries to kill executing program
.SS Author
.IP \[bu] 2
Vittorio Zaccaria
.SS License
.PP
Released under the BSD License.
.PP
   *   *   *   *   *
.SH New features
.IP \[bu] 2
increase timeout for older machines \-\- May 15th
16 (../../commit/583f792b045b8bfd18754d4c0e0c66a890aa57ee)
.IP \[bu] 2
log execution time \-\- May 15th
16 (../../commit/14b0f8cba9968304131390e850b0124837ae8cfe)
.IP \[bu] 2
update dockerfile \-\- May 10th
16 (../../commit/6f15b16b01baff2f27797dcddcb2cf84f31a3332)
.IP \[bu] 2
some changes to the documentation \-\- May 4th
16 (../../commit/6185b6a6c1231351965ff302933a68345a321809)
.IP \[bu] 2
add script for integration test \-\- May 3rd
16 (../../commit/391bdd398842d42a890ce906b9e180dffe2f38c4)
.IP \[bu] 2
add timeout \-\- May 3rd
16 (../../commit/62edb6b7807e2ee9f46b6f008ee46fe888d87d7b)
.IP \[bu] 2
add docker tls verify \-\- Apr 29th
16 (../../commit/59c4e8f20689a5945b9449f44921e7637a7cd38e)
.IP \[bu] 2
add makefile and tls verify to kube\-up \-\- Apr 28th
16 (../../commit/7bba227b6a644e3cb60f9091506ef81d183dadb5)
.IP \[bu] 2
add concurrent requests setting \-\- Apr 26th
16 (../../commit/c6cba1e58a1b7fba50f9d297d95ba27d6f458d75)
.IP \[bu] 2
working towards kubernetes containerization \-\- Apr 20th
16 (../../commit/31f589b303c58322434bd4d8400c4b942dd38fd0)
.IP \[bu] 2
add busy indicator \-\- Apr 12th
16 (../../commit/cf7dd4f940e3281c1f8153774b1e74a5ea3683a9)
.IP \[bu] 2
add run payload \-\- Apr 12th
16 (../../commit/5e1138c6173dc689add3fcfd279d455e4cfe96d2)
.IP \[bu] 2
add request parse \-\- Apr 11th
16 (../../commit/d0b904b1c44e9b584ee087ce7cae33f8fd83e87b)
.IP \[bu] 2
add sandbox creation and command execution \-\- Apr 8th
16 (../../commit/10f645ea5d46c065492a9716d1e4d1b14be4195e)
.IP \[bu] 2
add interactive nodemon development \-\- Apr 6th
16 (../../commit/c3d3a03c6509d816aafde1f222a1179135209f18)
.SH Bug fixes
.IP \[bu] 2
handle exception on the processRequest path \-\- Aug 29th
16 (../../commit/aff6daf001aa05bee28f4eb06efb7054a5346c55)
.IP \[bu] 2
changes to enable position independent read of docs/usage \-\- Jul 15th
16 (../../commit/e55ef0228b0575f279ac93358a8eb445a5d9ecbb)
.IP \[bu] 2
issue with html entities \-\- May 19th
16 (../../commit/033412c1067d39eae6bf6b3799c7bcab5a452ea0)
.IP \[bu] 2
increase timout \-\- May 17th
16 (../../commit/8404dc14a34c607ebfbc41890ff60c9368e846a6)
.IP \[bu] 2
remove mocha timeouts \-\- May 15th
16 (../../commit/e9c13e228eea4db7b13509d7d1c6a5abcc8b013f)
.IP \[bu] 2
answer format \-\- May 11th
16 (../../commit/6f048cc9a9f1b23dba33fb24746ac8d549b18b87)
.IP \[bu] 2
remove wrong nesting \-\- May 10th
16 (../../commit/3738604c32fedfc812d09019c98b7a0419954d5c)
.IP \[bu] 2
test output \-\- May 3rd
16 (../../commit/807839d9799d7796b25d8b5f1e4692c919b4834d)
.IP \[bu] 2
test port \-\- Apr 24th
16 (../../commit/04ac16d3b5583b3fe4361848fd063b4f2b8cb3bd)
.IP \[bu] 2
add missing dep \-\- Apr 24th
16 (../../commit/266319f825049f4b1cdfcedbdf29fcc7e72dd3ee)
.IP \[bu] 2
update deps \-\- Apr 24th
16 (../../commit/2c4dd07746740dce6ec01aa7efb0659f8bb1340f)
.IP \[bu] 2
missing lodash package \-\- Apr 24th
16 (../../commit/0f277a0e0c9e36da0c4013d78f8eed6adc413ee2)
.IP \[bu] 2
add missing makefile \-\- Apr 24th
16 (../../commit/a6a50270a6627fddcbeb0b40c3aad11b411d7bbe)
.IP \[bu] 2
end2end tests \-\- Apr 21st
16 (../../commit/486b2c800f998cf5097c7ba05c47a7a0b1143102)
.IP \[bu] 2
getting the wrong response \-\- Apr 20th
16 (../../commit/32d184d80db5a92aeb6cfd0d3ccf1dbe4d8baa19)
.IP \[bu] 2
change api endpoint name for the better \-\- Apr 12th
16 (../../commit/c8f7257c86ea6e144f8126c5c5a394dbe5761fd3)
.IP \[bu] 2
inject deps into the app \-\- Apr 12th
16 (../../commit/5b29f476495df71b3037313536a33d812f5e0492)
