.TH "" "" "" "" ""
.SH vz\-dockerino
.RS
.PP
Small container to execute external student octave programs
.RE
.SS Install
.PP
Install it with
.IP
.nf
\f[C]
npm\ install\ vz\-dockerino
\f[]
.fi
.SS Usage
.IP
.nf
\f[C]
Usage:
\ \ \ \ vz\-dockerino\ [\ \-p\ PORT\ ]
\ \ \ \ vz\-dockerino\ (\ \-h\ |\ \-\-help\ )

Options:
\ \ \ \ \-h,\ \-\-help\ \ \ \ \ \ \ \ \ \ \ \ \ \ help\ for\ vz\-dockerino
\ \ \ \ \-p,\ \-\-port\ PORT\ \ \ \ \ \ \ \ \ port\ on\ which\ to\ listen

Commands:

Arguments:
\f[]
.fi
.SS API
.PP
The server exposes two endpoints at port 3000
.SS \f[C]post\ /payload\f[]
.PP
Executes an EDX payload with the following schema:
.IP
.nf
\f[C]
{
\ \ \ \ code\ {
\ \ \ \ base,\ solution,\ validation,\ context,\ lang
\ \ \ \ }
\ \ \ \ response
}
\f[]
.fi
.PP
Answers:
.IP \[bu] 2
200 \- OK, result payload
.IP \[bu] 2
503 \- Server unavailable
.SS \f[C]post\ /status\f[]
.PP
No schema needed; returns:
.IP \[bu] 2
204 \- server ready
.IP \[bu] 2
503 \- Server unavailable (candidate for destruction)
.SS Todo
.PP
Add the following API endpoints:
.SS \f[C]post\ /kill\f[]
.IP \[bu] 2
Tries to kill executing program
.SS Author
.IP \[bu] 2
Vittorio Zaccaria
.SS License
.PP
Released under the BSD License.
.PP
   *   *   *   *   *
.SH New features
.IP \[bu] 2
add busy indicator \-\- Apr 12th
16 (../../commit/cf7dd4f940e3281c1f8153774b1e74a5ea3683a9)
.IP \[bu] 2
add run payload \-\- Apr 12th
16 (../../commit/5e1138c6173dc689add3fcfd279d455e4cfe96d2)
.IP \[bu] 2
add request parse \-\- Apr 11th
16 (../../commit/d0b904b1c44e9b584ee087ce7cae33f8fd83e87b)
.IP \[bu] 2
add sandbox creation and command execution \-\- Apr 8th
16 (../../commit/10f645ea5d46c065492a9716d1e4d1b14be4195e)
.IP \[bu] 2
add interactive nodemon development \-\- Apr 6th
16 (../../commit/c3d3a03c6509d816aafde1f222a1179135209f18)
.SH Bug fixes
.IP \[bu] 2
change api endpoint name for the better \-\- Apr 12th
16 (../../commit/c8f7257c86ea6e144f8126c5c5a394dbe5761fd3)
.IP \[bu] 2
inject deps into the app \-\- Apr 12th
16 (../../commit/5b29f476495df71b3037313536a33d812f5e0492)
